/**
 ******************************************************************************
 * @file      serial_io_hal.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE functions to set the serial port as
 *   		 characters input/output
 *  			 Set the "PRINT_SERIAL" constant to 1 to use serial port
 *  			 as characters input/output
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

$(include)

#include "serial_io.h"

int __io_putchar(int ch) __attribute__((weak, alias ("__serial_io_putchar")));
int __io_getchar(void) __attribute__((weak, alias ("__serial_io_getchar")));

/* UART handler declaration */
UART_HandleTypeDef UartHandle;

void __serial_io_init() {
	/*## Configure the UART peripheral ##############################*/
	/* Put the USART peripheral in the Asynchronous mode (UART Mode) */
	/* UART configured as follow:
	    - BaudRate = 115200 baud
	    - Word Length = 8 Bits
	    - Stop Bit = One Stop bit
	    - Parity = none
	    - Hardware flow control disabled (RTS and CTS signals) */

	UartHandle.Init.BaudRate   = 115200;
	UartHandle.Init.WordLength = UART_WORDLENGTH_8B;
	UartHandle.Init.StopBits   = UART_STOPBITS_1;
	UartHandle.Init.Parity     = UART_PARITY_NONE;
	UartHandle.Init.HwFlowCtl  = UART_HWCONTROL_NONE;
	UartHandle.Init.Mode       = UART_MODE_TX_RX;

	BSP_COM_Init(COM1, &UartHandle);

	// This is just to keep Eclipse happy, but generates no code; without this
	// Eclipse will generate an "unused" warning for the weak declarations above.
	if (0) __io_putchar(__io_getchar());
}


int __serial_io_putchar(int ch)
{
	/* Write a character to the EVAL_COM1 and Loop until transmitted */
	HAL_UART_Transmit(&UartHandle, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
   	return ch;
}

int __serial_io_getchar(void)
{
	int ch;
	/* Read a character from the EVAL_COM1 and Loop until received */
	HAL_UART_Receive(&UartHandle, (uint8_t *)&ch, 1, HAL_MAX_DELAY);
   	return ch;
}
