/**
 ******************************************************************************
 * @file      rsc_table.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Resources table file
 *
 *            This file provides a default resource table requested by
 *            remote proc to load the elf file. It also allows to add
 *            debug trace using a shared buffer.
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/** @addtogroup RSC_TABLE
  * @{
  */

/** @addtogroup stm32mp1xx_resource_table
  * @{
  */

/** @addtogroup STM32MP1xx_resource_table_Private_Includes
  * @{
  */

//#include "stm32mp1xx_hal.h"
#if defined(__ICCARM__)
#include <stddef.h> /* needed  for offsetof definition*/
#endif


/**
  * @}
  */

/** @addtogroup STM32MP1xx_resource_table_Private_TypesDefinitions
  * @{
  */


/**
  * @}
  */

/** @addtogroup STM32MP1xx_resource_table_Private_Defines
  * @{
  */
enum fw_resource_type {
	RSC_CARVEOUT = 0,
	RSC_DEVMEM = 1,
	RSC_TRACE = 2,
	RSC_VDEV = 3,
	RSC_LAST = 4,
};
/* Place resource table in special ELF section */
#if defined(__ICCARM__)
//#pragma section =".resource_table"
#elif defined(__GNUC__)
#define __section_t(S)          __attribute__((__section__(#S)))
#define __resource              __section_t(.resource_table)
#endif
struct fw_rsc_trace {
	unsigned int type;
	unsigned int da;
	unsigned int len;
	unsigned int reserved;
	unsigned char name[32];
} __packed;

/* Resource table for the given remote */
struct remote_resource_table {
	unsigned int version;
	unsigned int num;
	unsigned int reserved[2];
	unsigned int offset[1];
	struct fw_rsc_trace cm_trace;
};



#if defined (__LOG_TRACE_IO_)
extern char system_log_buf[];

#if defined(__ICCARM__)
__root struct remote_resource_table rproc_resource @ ".resource_table" = { \

	.version = 1, \
	.num = 1, \
	.reserved = {0, 0}, \
	.offset = { \
		offsetof(struct remote_resource_table, cm_trace), \
	}, \
	.cm_trace = {
		RSC_TRACE,
		(uint32_t)system_log_buf, SYSTEM_TRACE_BUF_SZ, 0, "cm4_log",
	},
};

#elif defined(__GNUC__)
struct remote_resource_table __resource __attribute__((used)) rproc_resource = { \

	.version = 1, \
	.num = 1, \
	.reserved = {0, 0}, \
	.offset = { \
		offsetof(struct remote_resource_table, cm_trace), \
	}, \
	.cm_trace = {
		RSC_TRACE,
		(uint32_t)system_log_buf, SYSTEM_TRACE_BUF_SZ, 0, "cm4_log",
	},
};
#endif

#else /* !__LOG_TRACE_IO_ */

#if defined(__ICCARM__)
__root struct remote_resource_table rproc_resource @ ".resource_table" = { \
	.version = 1,\
	.num = 0,\
	.reserved = {0, 0},\
	.offset = { 0 },\
};

#elif defined(__GNUC__)
struct remote_resource_table __resource __attribute__((used)) rproc_resource = { \
	.version = 1,\
	.num = 0,\
	.reserved = {0, 0},\
	.offset = { 0 },\
};
#endif


#endif /* __LOG_TRACE_IO_ */



