/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#warning "Secure / Non-Secure regions are not initialized. Please add code to properly initialize the Secure / Non-secure regions. This can be ignored if you know what you are doing."

int main(void)
{
	/**
	 * Add code here for initializing the non-secure stack pointer
	 * and then perform the jump to the non-secure reset handler
	 */
	for(;;);
}

/**
 * This function is Secure and is call-able from Non-Secure regions.
 */
__attribute__((cmse_nonsecure_entry)) int secure_add_one(int value) {
	return value + 1;
}
