/**
 ******************************************************************************
 * @file      serial_io.h
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE functions to set the serial port as
 *   		 characters input/output
 *  			 Set the "PRINT_SERIAL" constant to 1 to use serial port
 *  			 as characters input/output
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#ifndef SERIAL_IO_H_
#define SERIAL_IO_H_

/**
 * Define PRINT_SERIAL value at :
 * 	1 to redirect characters to the serial port
 *  0 to redirect characters to the LCD output (default)
 **/
#define PRINT_SERIAL	0


extern void __serial_io_init(void);
extern int __serial_io_putchar(int ch);
extern int __serial_io_getchar(void);


#endif /* SERIAL_IO_H_ */
